export type UiLanguage = 'en' | 'zh-CN';

export function isUiLanguage(value: unknown): value is UiLanguage {
  return value === 'en' || value === 'zh-CN';
}

export const chineseUi: Record<string, string> = {
  '{agent} continues the same line of inquiry with only this round’s changes.':
    '{agent} 将沿当前方向继续，只补充本轮变化。',
  '{agent} responds with a Reflection and supported next directions.':
    '{agent} 将返回分析回应与有依据的下一步方向。',
  '{count} directions will be reconsidered together. No Formal Nodes will be changed.':
    '将一起重新考虑 {count} 个方向，不修改任何正式节点。',
  'Read previous output: {title}': '阅读上一轮输出：{title}',
  '{name} is always included': '始终带入 {name}',
  'Edit {id}': '编辑 {id}',
  'Decompose from {id}': '从 {id} 开始分解',
  'Send revision to {agent}': '向 {agent} 发送修订',
  'Send to {agent}': '发送给 {agent}',
  '{agent} runs locally with your existing subscription login.':
    '{agent} 使用你已有的订阅登录在本地运行。',
  'Existing child boundaries will not be replaced. Add new evidence or guidance so {agent} can propose only genuinely new siblings.':
    '已有子节点的边界不会被替换。补充新的资料或说明，让 {agent} 只提出真正新增的同级节点。',
  Continue: '继续',
  'Ready to close': '可以收尾',
  'Consider branching': '考虑新分支',
  Settings: '设置',
  General: '通用',
  Language: '语言',
  'Interface language': '界面语言',
  'Personal settings for this local AgentManager installation.':
    '当前本地 AgentManager 的个人设置。',
  'Only website menus, buttons, and messages change. Your input, Agent responses, Markdown, and JSON stay exactly as they are.':
    '只改变网站菜单、按钮和提示的显示语言。你的输入、Agent 回答、Markdown 和 JSON 均保持原样。',
  'Saved automatically on this computer.': '自动保存在这台电脑上。',
  'Saving…': '正在保存…',
  Saved: '已保存',
  'Could not save settings.': '无法保存设置。',
  'Back to projects': '返回项目列表',
  Overview: '概览',
  'Product context': '产品上下文',
  "What's next": '下一步',
  Decomposition: '任务分解',
  Dependencies: '依赖关系',
  'Project navigation': '项目导航',
  'Switch project': '切换项目',
  Soon: '即将推出',
  Repository: '代码仓库',
  'Project workspace': '项目工作区',
  'Local only': '仅限本地',
  Projects: '项目',
  'Begin with a project boundary.': '从创建一个项目开始。',
  'Register a product idea or an existing code repository. Planning data stays beside the project while remaining invisible to its code history.':
    '创建一个产品想法，或关联已有代码仓库。规划数据保存在项目旁，不影响代码的提交历史。',
  'New project': '新建项目',
  'Create a project': '创建项目',
  'Choose where the project lives, then add only enough context to recognize it.':
    '选择项目位置，再填写名称和简短说明。',
  'Starting point': '起点',
  'Product idea': '产品想法',
  'No code repository yet': '还没有代码仓库',
  'Code repository': '代码仓库',
  'Attach existing local code': '关联已有本地代码',
  'Project name': '项目名称',
  Description: '简介',
  'Project directory': '项目目录',
  'Choose an existing local directory': '选择已有的本地目录',
  'A local-first workspace for one person building with agents.':
    '面向个人与 Agent 协作开发的本地工作区。',
  'AgentManager creates a locally excluded .agent-manager directory inside this folder.':
    'AgentManager 会在此文件夹内创建 .agent-manager 目录，并在本地排除其 Git 跟踪。',
  'Create the first project': '创建第一个项目',
  'Choose a folder, add a name, and write one short description.':
    '选择文件夹，填写名称和简短简介。',
  Choose: '选择',
  'Choosing…': '正在选择…',
  'Create project': '创建项目',
  'Creating…': '正在创建…',
  'Project overview': '项目概览',
  'No project description yet.': '尚未填写项目简介。',
  'Product sources': '产品资料',
  'Decomposition nodes': '分解节点',
  'Workspace ready': '工作区已就绪',
  'The project boundary is connected.': '项目目录已关联。',
  'Product context, decomposition, and dependency sync will be added as focused capabilities.':
    '在这里使用产品上下文、任务分解和依赖同步等功能。',
  'Next: product context': '下一步：产品上下文',
  'Add document': '添加文档',
  'Add feedback': '添加反馈',
  'Add or import a document for this folder.': '为此文件夹创建或导入文档。',
  'Add project-specific guidance and reference files that should be available whenever this feature asks an Agent to decompose work.':
    '添加项目专属说明和参考文件，供 Agent 分解任务时使用。',
  'Additional Context Library Resources': '补充上下文库资料',
  'Additional Local Markdown': '补充本地 Markdown',
  'Additional Resource folder': '补充资料文件夹',
  Ask: '提问',
  Assumptions: '假设',
  Attachments: '附件',
  'Break one scope into coherent, human-manageable nodes.':
    '把一个范围分解成连贯、便于理解的节点。',
  Cancel: '取消',
  'Cancel Agent Run': '取消 Agent 运行',
  Candidate: '候选',
  'Candidate · revision': '候选 · 版本',
  'Clear selected feedback text': '清除选中的反馈文本',
  'Clear the selection': '清除选择',
  Close: '关闭',
  'Close JSON preview': '关闭 JSON 预览',
  'Close Markdown reader': '关闭 Markdown 阅读器',
  'Close focus reading': '关闭专注阅读',
  Combine: '组合',
  'Compare with previous revision': '与上一版对比',
  Context: '上下文',
  'Context Library folder': '上下文库文件夹',
  'Context library': '上下文库',
  'Context sections': '上下文分类',
  'Create Start': '创建起点',
  'Create a flexible Product Context section. A README can be added later.':
    '创建产品上下文分类，之后可以添加 README。',
  'Create a readable Markdown file inside': '在此处创建 Markdown 文件：',
  'Create the fixed Product, Design, Engineering, Milestones, References, and Other folders with README guidance for people and agents.':
    '创建 Product、Design、Engineering、Milestones、References 和 Other 文件夹，并附上供人与 Agent 阅读的 README 说明。',
  Created: '创建时间',
  'Created through': '创建方式',
  'Decomposition canvas': '任务分解画布',
  'Decomposition instructions': '分解说明',
  'Decomposition workspace': '任务分解工作区',
  Delete: '删除',
  'Delete Markdown document': '删除 Markdown 文档',
  'Delete document': '删除文档',
  'Delete node': '删除节点',
  'Delete this card': '删除此卡片',
  Dependents: '被依赖于',
  'Depends on': '依赖于',
  'Derived from': '派生自',
  'Derived nodes': '派生节点',
  'Describe project-specific constraints, preferred resolution, naming conventions, acceptance expectations, or anything the Agent should account for while decomposing this scope.':
    '填写项目约束、期望粒度、命名规则、验收要求，以及 Agent 分解此范围时需要注意的事项。',
  'Describe what should change…': '描述需要修改的内容…',
  Discard: '丢弃',
  'Discard Candidate': '丢弃候选',
  'Discard this direction': '丢弃此方向',
  'Document title': '文档标题',
  Documents: '文档',
  'Drop Markdown files here, or browse': '拖入 Markdown 文件，或点击选择',
  'Drop Markdown or choose files': '拖入 Markdown 或选择文件',
  'Edit source': '编辑来源',
  'Edit start node': '编辑起点',
  'Every changed line is shown before this revision is accepted.':
    '接受此版本前，可以查看每一处行级变化。',
  'Explore more': '继续探索',
  'Feedback for this Refine': '本次细化的反馈',
  Folder: '文件夹',
  'Folder name': '文件夹名称',
  'Graph canvas': '节点画布',
  'Graph details': '图关系详情',
  'Grew from': '来源节点',
  'Harness boundary': 'Harness 边界',
  'Import Markdown': '导入 Markdown',
  'Included automatically': '自动带入',
  'Inherited Resources': '继承的资料',
  'Inherited Resources stay on the source Node; additions apply only to this request.':
    '继承资料保留在来源节点上；新增资料仅用于本次请求。',
  'Initialize Product Context': '初始化产品上下文',
  'Inline feedback': '选区反馈',
  'Input from': '输入来源',
  Inputs: '输入',
  Instruction: '指令',
  Instructions: '说明',
  'Latest Response': '最新回答',
  Lineage: '派生关系',
  Lines: '行',
  'Local Markdown': '本地 Markdown',
  'Markdown and JSON references owned by this feature context.':
    '此功能上下文使用的 Markdown 和 JSON 参考资料。',
  'Markdown or JSON · 2 MB each': 'Markdown 或 JSON · 每个文件最多 2 MB',
  Metadata: '元数据',
  'New Folder': '新建文件夹',
  'New Markdown': '新建 Markdown',
  'New Markdown document': '新建 Markdown 文档',
  'New context folder': '新建上下文文件夹',
  'No Markdown documents': '没有 Markdown 文档',
  'No Markdown documents are available yet.': '尚无可用的 Markdown 文档。',
  'No attachments yet. Instructions can be used on their own.':
    '尚无附件，也可以只填写说明。',
  None: '无',
  'Open details': '打开详情',
  'Optional Resources for this Agent Run only':
    '可选资料，仅用于本次 Agent 运行',
  'Optional sources': '可选资料',
  Outputs: '输出',
  'Previous instruction': '上一轮指令',
  'Previous outputs ·': '上一轮输出 ·',
  'Previous proposal': '上一轮提案',
  'Previous proposal context': '上一轮提案上下文',
  'Read full last response': '阅读上一轮完整回答',
  'Redo proposal': '重做整轮提案',
  'Referenced by': '被引用于',
  Refine: '细化',
  'Refine this Markdown': '细化此 Markdown',
  Relationships: '关系',
  'Remove Resource': '移除资料',
  'Remove attachment': '移除附件',
  'Remove context attachment?': '移除此上下文附件？',
  'Remove inline feedback': '移除此反馈',
  'Remove source': '移除来源',
  'Rename context folder': '重命名上下文文件夹',
  'Rename folder': '重命名文件夹',
  'Rename the folder on disk without changing its documents.':
    '重命名磁盘上的文件夹，不改变其中的文档。',
  'Replace existing documents?': '覆盖已有文档？',
  Resources: '资料',
  Review: '审阅',
  Revise: '修订',
  Revision: '版本',
  'Revision note': '修订说明',
  Role: '角色',
  'Run-only context': '本次补充上下文',
  Save: '保存',
  'Select a section to read its purpose and Agent loading guidance. The folder structure is the source of truth.':
    '选择分类以阅读用途和 Agent 加载说明。文件夹结构即为实际结构。',
  'Select every document needed to understand what will be decomposed.':
    '选择理解此次分解范围所需的所有文档。',
  'Selected dependencies': '选中节点的依赖',
  'Selected text feedback': '选中文本反馈',
  'Show README folder in file manager': '在文件管理器中显示 README 文件夹',
  'Show in file manager': '在文件管理器中打开',
  'Source Markdown': '来源 Markdown',
  'Source proposal': '来源提案',
  'Stable ID': '稳定标识',
  Start: '起点',
  'Start and ask': '创建起点并提问',
  'Start-node title': '起点标题',
  Status: '状态',
  'The folder path uses an English slug.': '文件夹路径使用英文短名称。',
  'The name becomes an English slug such as research-notes.':
    '名称会转换为 research-notes 这样的英文短名称。',
  'The next revision is running.': '正在生成下一版。',
  'The title becomes an English slug such as product-foundation.md.':
    '标题会转换为 product-foundation.md 这样的英文文件名。',
  'Their output becomes the input for one question.':
    '这些节点的输出将作为一次提问的输入。',
  'This Candidate and its output will move to the operating system Trash. Other Candidates from the same proposal stay unchanged.':
    '此候选及其输出会移到系统回收站，同轮其他候选保持不变。',
  'This Node carries no Resources yet.': '此节点尚未附带资料。',
  'This folder has no Markdown documents.': '此文件夹没有 Markdown 文档。',
  'This folder is empty.': '此文件夹为空。',
  'This project has no Product Context library yet.':
    '此项目尚未建立产品上下文库。',
  Type: '类型',
  'Up to 20 files, 2 MB each': '最多 20 个文件，每个不超过 2 MB',
  Updated: '更新时间',
  'User-owned constraints and preferences. The feature Harness is separate and will not overwrite this file.':
    '由你管理的约束和偏好。功能 Harness 独立维护，不会覆盖此文件。',
  'What do you want to build?': '你想做一个什么样的产品？',
  'What do you want to do with these together?': '你想如何一起使用这些内容？',
  'What should the Agent reconsider here?': '你希望 Agent 重新考虑什么？',
  'What to do with the selected cards': '对选中卡片的要求',
  'Your idea': '你的想法',
  'always included': '始终带入',
  attached: '已附加',
  cards: '张卡片',
  'is working…': '正在工作…',
  more: '更多',
  selected: '已选择',
  '· revision': '· 版本',
  '· unaccepted direction': '· 未接受的方向',
  Accept: '接受',
  'Accepting…': '正在接受…',
  'Starting…': '正在启动…',
  'Start exploration': '开始探索',
  'Continue exploration': '继续探索',
  'Continue from': '继续探索自',
  'Explore from': '探索自',
  'Redo proposal from': '重做提案自',
  'Re-propose': '重新提案',
  Correction: '纠正说明',
  required: '必填',
  optional: '可选',
  'What did this proposal misunderstand, and what do you want instead?':
    '上一轮提案误解了什么？你实际想要什么？',
  'Steer this round, or let the Agent respond from the current Node.':
    '填写本轮要求，或让 Agent 从当前节点继续。',
  'Save changes': '保存修改',
  'Creating project…': '正在创建项目…',
  Edit: '编辑',
  'Choose files': '选择文件',
  Remove: '移除',
  Rename: '重命名',
  'Renaming…': '正在重命名…',
  Import: '导入',
  'Importing…': '正在导入…',
  'Deleting…': '正在删除…',
  Running: '运行中',
  Failed: '失败',
  Canceled: '已取消',
  Source: '来源',
  Preview: '预览',
  'Send Refine': '发送细化请求',
  Refining: '正在细化',
  'Close reader': '关闭阅读器',
  'Enable annotations': '开启标注',
  'Disable annotations': '关闭标注',
  'Open focus reading': '开启专注阅读',
  'Exit focus reading': '退出专注阅读',
  'Open focus mode': '开启专注模式',
  'Exit focus mode (Esc)': '退出专注模式（Esc）',
  'Zoom In': '放大',
  'Zoom Out': '缩小',
  'Fit View': '适应画布',
  'Project settings': '项目设置',
  'Accept revision': '接受此版本',
  'Add to selection': '加入选择',
  'Adding…': '正在添加…',
  'Context ready': '上下文已就绪',
  'Create context structure': '创建上下文结构',
  'Create document': '创建文档',
  'Create fixture request': '创建演示请求',
  'Create folder': '创建文件夹',
  'Create start node': '创建起点',
  Decompose: '分解',
  'Define this round of work. Inherited Resources stay on the source Node; additions apply only to this request.':
    '填写本轮任务要求。继承资料保留在来源节点上，新增资料仅用于本次请求。',
  'Delete the referencing cards first': '请先删除引用此卡片的节点',
  'Delete the referencing nodes first': '请先删除引用此节点的其他节点',
  'Describe how this Candidate itself should change.':
    '描述这张候选卡本身需要怎样调整。',
  'Describe the new evidence or boundary that may require additional siblings.':
    '说明可能需要新增同级节点的补充资料或边界。',
  'Development fixture only. Nothing is sent to an Agent.':
    '仅为开发演示，不会向 Agent 发送请求。',
  'Discarding…': '正在丢弃…',
  'Drop files or choose attachments': '拖入文件或选择附件',
  'Explore more adds directions without replacing the current proposal.':
    '继续探索会新增方向，不替换当前提案。',
  'Find additional nodes': '寻找补充节点',
  'Initializing…': '正在初始化…',
  'Manual creation': '手动创建',
  'Move node to Trash': '将节点移到回收站',
  'Move this card to Trash': '将卡片移到回收站',
  'New start node': '新建起点',
  'No description yet.': '尚无说明。',
  'No instruction was recorded for this proposal.':
    '此提案没有记录上一轮指令。',
  'Not configured': '尚未配置',
  Nothing: '无',
  'Open output.md': '打开 output.md',
  'Opening output…': '正在打开输出…',
  'Opening…': '正在打开…',
  'Preview only': '仅供预览',
  'Re-propose discards the current directions to system Trash and immediately generates a new proposal. Cancellation or failure does not restore discarded directions.':
    '重新提案会把当前方案移到系统回收站，并立即生成新提案。取消或失败都不会恢复已丢弃的方案。',
  'Redefine this Candidate only. Revisions cannot create siblings or child Nodes.':
    '只重新定义这张候选卡，不创建同级节点或子节点。',
  'Redo all unaccepted directions from this parent':
    '重做此父节点下所有尚未接受的方向',
  'Removing…': '正在移除…',
  Replace: '覆盖',
  'Replacing…': '正在覆盖…',
  'Save instructions': '保存说明',
  'The node folder will move to the operating system Trash. Its upstream relationships will disappear with it.':
    '节点文件夹会移到系统回收站，它与上游节点的关系也会移除。',
  'This removes the node from the development preview until the page reloads.':
    '从开发预览中移除此节点，刷新页面后恢复。',
  Unselect: '取消选择',
  'A manager that helps one developer grow and decompose product intent…':
    '一个帮助个人开发者逐步完善想法并分解产品内容的工具…',
  'AgentManager’s feature-level generation contract will be designed separately. It will consume this user context but remain independently versioned and replaceable.':
    'AgentManager 的功能生成契约独立设计。它会读取这些用户上下文，但独立维护版本，可单独替换。',
  'What&apos;s next': '下一步',
  "What's Next": '下一步',
  'Write the idea in your own words. It becomes the Start of this Canvas, and':
    '用自己的话描述想法。它会成为画布的起点，由',
  'answers it straight away.': '直接回答。',
  '. Delete those first.': '。请先删除它们。',
  '. Select them above and delete them first.': '。请先在上方选择并删除它们。',
  '. Existing directions and dependencies remain unchanged.':
    '。现有方向和依赖关系保持不变。',
  '/ 100,000 characters': '/ 100,000 字符',
  '/4,000 characters': '/4,000 字符',
  'A captured': '已记录的',
  'This removes the Markdown file from the project. The':
    '这会移除项目中的 Markdown 文件，但',
  'folder will remain.': '文件夹会保留。',
  'This rewrites the Markdown carried by': '这会改写以下节点中的 Markdown：',
  'node and its fixed source boundary.': '节点及其固定的来源边界。',
  already: '已经存在',
  'in this folder. Importing will replace the existing':
    '在此文件夹中。导入会覆盖已有的',
  'will be deleted from this project’s Decomposition context folder.':
    '将从此项目的任务分解上下文文件夹中删除。',
  'Revision {revision} · {count} Resources': '版本 {revision} · {count} 份资料',
  'Open details for {title}': '打开详情：{title}',
  "Ask what's next": '探索下一步',
  '{action} from {title}': '从「{title}」{action}',
  'Add feedback for lines {start} to {end}': '为第 {start} 至 {end} 行添加反馈',
};

export function translateUi(
  language: UiLanguage,
  text: string,
  values: Record<string, string | number> = {},
) {
  const message = language === 'zh-CN' ? (chineseUi[text] ?? text) : text;
  return message.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : match,
  );
}
